FROM python:3.12-slim

ENV PYTHONPATH=/app

WORKDIR /app

COPY requirements.txt .

COPY alembic.ini .

COPY ./entrypoint.sh .

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY tests .

EXPOSE 8000

ENTRYPOINT [ "./entrypoint.sh" ]

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
