"""

Revision ID: 1cd378287ca4
Revises: b9427b47082b
Create Date: 2026-04-15 11:37:14.857187+00:00

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1cd378287ca4"
down_revision = "b9427b47082b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("totp_secret", sa.String(length=64), nullable=True)
    )
    op.add_column("users", sa.Column("totp_enabled", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "totp_enabled")
    op.drop_column("users", "totp_secret")
    # ### end Alembic commands ###
